// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { createRequire } = require('node:module')
require = createRequire(__filename)

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function registerNodeWasmRuntime(binding) {
  if (
    typeof binding?.__registerNodeWasmRuntime !== 'function' ||
    typeof binding?.__nodeWasmImportCall !== 'function'
  ) {
    return
  }

  let WASI
  const modules = new Map()
  const instances = new Map()
  const debugNodeWasm = (...args) => {
    if (process.env.RSPACK_DEBUG_NODE_WASM && process.env.RSPACK_DEBUG_NODE_WASM !== '0') {
      console.error('[rspack:node-wasm-runtime]', ...args)
    }
  }

  const getInstance = (instanceId) => {
    const state = instances.get(instanceId)
    if (!state) {
      throw new Error(`SWC Wasm plugin instance ${instanceId} does not exist`)
    }
    return state
  }

  binding.__registerNodeWasmRuntime({
    compile(moduleId, bytes) {
      debugNodeWasm('compile', moduleId, bytes.length)
      modules.set(moduleId, new WebAssembly.Module(bytes))
    },
    instantiate(instanceId, moduleId, importNames, envsJson) {
      debugNodeWasm('instantiate:start', instanceId, moduleId, importNames.length)
      const mod = modules.get(moduleId)
      if (!mod) {
        throw new Error(`SWC Wasm plugin module ${moduleId} does not exist`)
      }

      const importObject = {
        env: Object.create(null),
      }

      for (let index = 0; index < importNames.length; index++) {
        importObject.env[importNames[index]] = (...args) => {
          debugNodeWasm('import', instanceId, index, importNames[index], args)
          const results = binding.__nodeWasmImportCall(
            instanceId,
            index,
            args,
            getInstance(instanceId).memory.buffer,
          )
          debugNodeWasm('import:return', instanceId, index, results)
          if (results.length === 0) {
            return
          }
          if (results.length === 1) {
            return results[0]
          }
          return results
        }
      }

      const env = Object.create(null)
      for (const [key, value] of JSON.parse(envsJson)) {
        env[key] = value
      }

      WASI ??= require('node:wasi').WASI
      const wasi = new WASI({
        version: 'preview1',
        args: [],
        env,
        preopens: {
          '/cwd': process.cwd(),
        },
        returnOnExit: true,
      })
      importObject.wasi_snapshot_preview1 = wasi.wasiImport

      const instance = new WebAssembly.Instance(mod, importObject)
      debugNodeWasm('instantiate:created', instanceId)
      const exports = instance.exports
      const memory = exports.memory
      const alloc = exports.__alloc
      const free = exports.__free
      const transform = exports.__transform_plugin_process_impl
      const coreDiag = exports.__get_transform_plugin_core_pkg_diag

      if (!(memory instanceof WebAssembly.Memory)) {
        throw new Error('SWC Wasm plugin does not export WebAssembly.Memory as "memory"')
      }
      if (typeof alloc !== 'function') {
        throw new Error('SWC Wasm plugin does not export "__alloc"')
      }
      if (typeof free !== 'function') {
        throw new Error('SWC Wasm plugin does not export "__free"')
      }
      if (typeof transform !== 'function') {
        throw new Error('SWC Wasm plugin does not export "__transform_plugin_process_impl"')
      }
      if (typeof coreDiag !== 'function') {
        throw new Error('SWC Wasm plugin does not export "__get_transform_plugin_core_pkg_diag"')
      }

      const state = {
        instance,
        memory,
        alloc,
        free,
        transform,
        wasi,
      }
      instances.set(instanceId, state)
      debugNodeWasm('instantiate:wasi.initialize', instanceId)
      wasi.initialize(instance)
      debugNodeWasm('instantiate:coreDiag', instanceId)
      coreDiag()
      debugNodeWasm('instantiate:done', instanceId)
    },
    transform(instanceId, programPtr, programLen, unresolvedMark, shouldEnableCommentsProxy) {
      debugNodeWasm('transform', instanceId, programPtr, programLen)
      return getInstance(instanceId).transform(
        programPtr,
        programLen,
        unresolvedMark,
        shouldEnableCommentsProxy,
      ) >>> 0
    },
    alloc(instanceId, size) {
      return getInstance(instanceId).alloc(size) >>> 0
    },
    free(instanceId, ptr, size) {
      return getInstance(instanceId).free(ptr, size) >>> 0
    },
    read(instanceId, ptr, len) {
      const { memory } = getInstance(instanceId)
      return Buffer.from(new Uint8Array(memory.buffer, ptr, len))
    },
    write(instanceId, ptr, bytes) {
      const { memory } = getInstance(instanceId)
      new Uint8Array(memory.buffer, ptr, bytes.length).set(bytes)
    },
    dropInstance(instanceId) {
      instances.delete(instanceId)
    },
    dropModule(moduleId) {
      modules.delete(moduleId)
    },
  })
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./rspack.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-android-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./rspack.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-android-arm-eabi')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./rspack.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-win32-x64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./rspack.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-win32-ia32-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./rspack.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-win32-arm64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./rspack.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      return require('@rspack/binding-darwin-universal')
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./rspack.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-darwin-x64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./rspack.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-darwin-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./rspack.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-freebsd-x64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./rspack.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-freebsd-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./rspack.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@rspack/binding-linux-x64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rspack.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@rspack/binding-linux-x64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./rspack.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@rspack/binding-linux-arm64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rspack.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@rspack/binding-linux-arm64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./rspack.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@rspack/binding-linux-arm-musleabihf')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rspack.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@rspack/binding-linux-arm-gnueabihf')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./rspack.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@rspack/binding-linux-riscv64-musl')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./rspack.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return require('@rspack/binding-linux-riscv64-gnu')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./rspack.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-linux-ppc64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./rspack.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-linux-s390x-gnu')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./rspack.linux-arm64-ohos.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-linux-arm64-ohos')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./rspack.linux-x64-ohos.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-linux-x64-ohos')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./rspack.linux-arm-ohos.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@rspack/binding-linux-arm-ohos')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  try {
    nativeBinding = require('./rspack.wasi.cjs')
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
  if (!nativeBinding) {
    try {
      nativeBinding = require('@rspack/binding-wasm32-wasi')
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        loadErrors.push(err)
      }
    }
  }
}

if (!nativeBinding && globalThis.process?.versions?.["webcontainer"]) {
  try {
    nativeBinding = require("./webcontainer-fallback.cjs")
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.' +
        `\n\n${loadErrors.map((e) => e.message).join('\n')}`,
      { cause: loadErrors }
    )
  }
  throw new Error(`Failed to load native binding`)
}

registerNodeWasmRuntime(nativeBinding)

module.exports.default = module.exports = nativeBinding
